language: rust

rust:
  - 1.20.0
  - stable
  - beta
  - nightly

env:
  - RUST_BACKTRACE=1

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo test --verbose
  - cargo test --verbose --no-default-features --features ncurses-backend
  - cargo test --verbose --no-default-features --features panncurses-backend
  - cargo test --verbose --no-default-features --features ncurses-backend
  - cargo test --verbose --no-default-features --features blt-backend
