[package]
name = "tg-tui"
version = "0.1.0"
authors = ["hcpl <hcpl.prog@gmail.com>"]

[dependencies]
app_dirs = "1.1.1"
clap = "2.26.0"
cursive = "0.6.2"
error-chain = "0.10.0"
rand = "0.3.16"
time = "0.1.38"
