[package]
name = "tg-tui"
version = "0.1.0"
description = "Terminal user interface client for Telegram"
authors = ["hcpl <hcpl.prog@gmail.com>"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/hcpl/tg-tui"
repository = "https://github.com/hcpl/tg-tui"

[dependencies]
app_dirs = "1.1.1"
clap = "2.26.0"
config = "0.7.0"
cursive = "0.6.2"
error-chain = "0.10.0"
rand = "0.3.16"
textwrap = "0.7.0"
time = "0.1.38"
